### ISSUE TITLE
PDF file conversion fails, prompting encoding error

### ISSUE THREAD

**Issue by PlatonaBoy** [freedmand/semantra#15]
![image](https://user-images.githubusercontent.com/80155818/234792119-6764d0a9-3ea5-4ea0-817d-0d44a2d90caa.png)
When parsing the pdf file, it prompts that the code conversion error is wrong. This is because I have not set the parameters, or there is such a problem.

**Comment by freedmand** [comment]
Hi, thanks for raising the issue.

I recently updated Semantra to address this issue. If you run `semantra --version` you can see what version you're currently running. Version 0.1.3 and above has the fix.

You can update Semantra to the current version by running `pipx upgrade semantra`.

If the issue is still persisting and `semantra --version` is showing >0.1.3, let me know!
