### ISSUE TITLE
Non-English models

### ISSUE THREAD

**Issue by git4ai** [freedmand/semantra#19]
semantra works very well on English articles.
But I encountered some obstacles on Chinese articles.

I have installed a bert chinese model on PowerShell:

`PS D:\semantra> semantra.exe --transformer-model ckiplab/bert-base-chinese C:\Users\xxx\Desktop\booktxt\*.txt`

but I got this:

![screenshot20230428](https://user-images.githubusercontent.com/112789662/235131826-41e082bc-2dfd-4076-95d9-b4e852d9594f.png)

What should I fix? Thank you!

**Comment by freedmand** [comment]
This is indeed a bug, and probably something related to encodings. Can you send me any example document along with the command-line parameters you used with Semantra? I will see if I can reproduce it. Thanks for flagging!

**Comment by git4ai** [comment]
Sure!
[唐吉诃德(上).txt](https://github.com/freedmand/semantra/files/11355157/default.txt)
[唐吉诃德(下).txt](https://github.com/freedmand/semantra/files/11355158/default.txt)
[唐吉诃德(中).txt](https://github.com/freedmand/semantra/files/11355160/default.txt)

This is Don Quixote btw ;->

**Comment by freedmand** [comment]
Ok, making headway! I think the issue here is that the `.txt` files are not `utf-8` encoded (which is what Semantra currently expects). From trial-and-error, they appear to be `gb18030` encoded. I'm creating a parameter `--encoding` you can pass to Semantra to specify when it's non-utf8.

Does this look like plausible results? I don't speak Chinese so it's hard for me to verify it's working 🙃 . You can pass me a query to try if you like, too.

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/306095/235307449-9b7a94a1-7c59-40d5-9d11-565df2903bc5.png">

**Comment by freedmand** [comment]
I just converted one of the files to PDF. Let me know also if the results look accurate for this, too! For the PDF file, the encoding does not need to be specified since it is embedded in the format.

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/306095/235307819-d0bad23f-f707-4825-9c15-a6dce5c6ee63.png">

**Comment by freedmand** [comment]
Just merged this in. Semantra `0.1.6` contains the fix. You can upgrade by running `pipx upgrade semantra` and double-check the version via `semantra --version`. Please reopen if it doesn't work, and thank you!

**Comment by git4ai** [comment]
Thank you very much for your help!

I upgraded to `0.1.6`, but still didn't get the desired result, semantra query is still garbled, but I got the desired result by converting the file encoding.

```
PS D:\semantra> semantra.exe --version
0.1.6
```

I checked the original txt file in notepad++ and it shows the encoding as GB2312.

![屏幕截图 2023-05-01 215935](https://user-images.githubusercontent.com/112789662/235463805-e5a13e55-41ec-45e5-b54b-56dfcd3f0c64.png)

Now I get the correct expectation by your two methods:

- file-GB2312.txt -> file-UTF-8.txt - OK
- file-GB2312.txt -> file.pdf - OK

I have tons of text files I want to work with, so maybe I should try batch converting the file encoding. Also maybe look for other Chinese models, it's a bit deep for me.

Thanks a lot!
