### ISSUE TITLE
How to know which Hugging Face Hub models can be used?

### ISSUE THREAD

**Issue by geigerX** [freedmand/semantra#45]
According to _guide_models.md_, many models in the Hugging Face Hub can be used by Semantra. But how to know which Hugging Face Hub models can be used?
How can we determine whether an error encountered when executing the "--transformer-model" command is due to the unavailability of the model or other factors such as computer configuration?

**Comment by endolith** [comment]
> any [pretrained Sentence Transformers model](https://huggingface.co/models?library=sentence-transformers) can be used

These are listed on https://www.sbert.net/docs/pretrained_models.html

**Comment by geigerX** [comment]
> > any [pretrained Sentence Transformers model](https://huggingface.co/models?library=sentence-transformers) can be used
> 
> These are listed on https://www.sbert.net/docs/pretrained_models.html
> 
> For instance, `--transformer-model sentence-transformers/paraphrase-multilingual-mpnet-base-v2` works for me.

Yes, same question as in #53 , do others work?

**Comment by freedmand** [comment]
You can use many HuggingFace transformers models — it's certainly not limited to Sentence Transformers at all. If you look at the [models guide](https://github.com/freedmand/semantra/blob/main/docs/guide_models.md) you will see some other HuggingFace models outside of Sentence Transformers (sgpt) that have proven to be effective. Anything branded for semantic similarity will likely work well with Semantra.

It's possible that almost any HuggingFace model will technically work, since they all have an inner layer that can be used for embeddings (and I coded it to be as flexible as possible), but these embeddings will not necessarily be any good for the purpose of semantic similarity. For instance, you can use [gpt2](https://huggingface.co/gpt2) as a model, and the search results may even be relevant, but they might not be as effective compared to other models of similar sizes trained on the task of semantic similarity. If there is a HuggingFace model that you expect to work, and it has an error, please file an issue.
